[project]
name = "bssir"
version = "0.6.8"
description = "Shared data-loading and transformation utilities for Iranian socioeconomic surveys."
readme = "README.md"
authors = [
  { name = "Mohammad Amin Alavian", email = "m.amin.alavian@gmail.com" }
]
keywords = ["iran", "survey", "data", "socioeconomic"]
requires-python = ">=3.12"
dependencies = [
  "dataforgeir",
  "pandas>=2",
  "pyarrow",
  "PyYAML",
  "pydantic>=2",
  "requests",
  "tqdm>=4.67.1",
  "rich>=14.2.0",
]

[project.optional-dependencies]

# Storage backends
s3 = [
  "boto3",
  "boto3-stubs[s3]",
]

build = [
  "dbfread",
  "openpyxl>=3.1.5",
  "pyodbc",
  "rarfile>=4.3",
]

# Plotting
plot = [
  "seaborn",
]

# Documentation
docs = [
  "mkdocs",
  "mkdocs-material",
  "mkdocs-literate-nav",
  "mkdocs-autorefs",
  "mkdocstrings-python",
  "mkdocs-jupyter",
]

# Notebook support
notebook = [
  "ipykernel",
  "ipywidgets",
]

# Development tools
dev = [
  "black",
  "pytest",
  "ruff>=0.14.0",
]

all = [
  "bssir[s3]",
  "bssir[s3-dev]",
  "bssir[excel]",
  "bssir[parquet]",
  "bssir[plot]",
  "bssir[docs]",
  "bssir[notebook]",
  "bssir[dev]",
]

[project.urls]
Homepage = "https://github.com/Iran-Open-Data/BSSIR"
Repository = "https://github.com/Iran-Open-Data/BSSIR"

[tool.uv]
package = true

[tool.uv.workspace]
members = [
  ".",
]

[tool.uv.sources]
bssir = { workspace = true, editable = true }
dataforgeir = { path = "../DataForgeIR", editable = true }

[dependency-groups]
dev = [
  "bssir",
  "ruff>=0.14.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
bssir = ["**/*.yaml", "**/*.csv"]
