# Package Name
package_name: BSSIR

# Years (list of years or range in for of: "first_year - last_year")
years: "1363-1402"

# Package Settings
package_settings: config/settings.yaml

# Local Settings
local_settings: config/settings.yaml

# Local Directory
local_dir: Data
in_root: true

# Download Source
default_download_source: original
private_data: false

# Mirrors
mirrors:
  - name: arvan
    endpoint: https://s3.ir-tbz-sh1.arvanstorage.ir
    bucket_name: iran-open-data
  - name: amazon
    endpoint: https://iran-open-data.s3.us-east-2.amazonaws.com
    bucket_name: iran-open-data
default_mirror: arvan

# Folder Names
folder_names:
  cached: _cache
  metadata: _metadata
  original: 1_original
  unpacked: 2_unpacked
  extracted: 3_extracted
  cleaned: 4_cleaned
  external: external
  maps: maps

# Map
default_map: humandata

## Functions
functions:
  ## Setup Raw Data
  setup_raw_data:
    replace: false
    download_source: original

  ## Load Table
  load_table:
    years: last
    form: normalized
    on_missing: create
    save_downloaded: true
    redownload: false
    save_created: true
    recreate: false

  ## Load External Table
  load_external_table:
    form: cleaned
    on_missing: download
    save_downloaded: true
    redownload: false
    save_created: true
    recreate: false

# Columns
columns:
  year: Year
  id: ID
  weight: Weight

  commodity_code: [commodity, coicop]
  industry_code: [industry, isic]
  occupation_code: [occupation, isco]

  groupby: [Urban_Rural, Province, County, Decile, Percentile]

# Metadata
## Base Package Metadata
base_package_metadata:
  instruction: metadata/_instruction.yaml
  raw_files: metadata/raw_files.yaml
  tables: metadata/tables.yaml
  maps: metadata/maps.yaml
  id_information: metadata/id_information.yaml
  commodities: metadata/commodities.yaml
  occupations: metadata/occupations.yaml
  industries: metadata/industries.yaml
  schema: metadata/schema.yaml

## Package Metadata
package_metadata:
  instruction: metadata/_instruction.yaml
  raw_files: metadata/raw_files.yaml
  tables: metadata/tables.yaml
  maps: metadata/maps.yaml
  id_information: metadata/id_information.yaml
  commodities: metadata/commodities.yaml
  occupations: metadata/occupations.yaml
  industries: metadata/industries.yaml
  schema: metadata/schema.yaml

## Local Metadata
local_metadata:
  instruction: metadata/_instruction.yaml
  raw_files: metadata/raw_files.yaml
  tables: metadata/tables.yaml
  maps: metadata/maps.yaml
  id_information: metadata/id_information.yaml
  commodities: metadata/commodities.yaml
  occupations: metadata/occupations.yaml
  industries: metadata/industries.yaml
  schema: metadata/schema.yaml

## Documentations
docs:
  csv: temp/csv
  raw_tables: tables/raw
  cleaned_tables: tables/cleaned
